- name: Run Python script on routers
  hosts: routers
  gather_facts: no
  tasks:
    - name: Execute Python script
      command: python3 python-script.py
      register: script_output

    - name: Print script output
      debug:
        var: script_output.stdout_lines

- name: Run Python script on switches
  hosts: switch
  gather_facts: no
  tasks:
    - name: Execute Python script
      command: python3 python-script-switch.py
      register: script_output

    - name: Print script output
      debug:
        var: script_output.stdout_lines
